services:

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - mongoCreds.env
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - mongoExpressCreds.env

# Named volumes for persisting necessary containers' data across restart.
volumes:
  mongo-data:
