# Version of docker-compose file is no longer required
version: '3.3'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - pgCreds.env
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - pgAdminCreds.env
    ports:
      - 8088:80
    networks:
      - pg-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

# Bridge type of network connecting to both (postgres, pgadmin) containers.
# As recommended by docker (https://docs.docker.com/network/bridge)
networks:
  pg-network:
    name: pg-network
    driver: bridge

# Named volumes for persisting necessary containers' data across restart.
volumes:
  pg-data:
  pgadmin-data:
